import type { CheckFinding, CheckReport } from '../../src/check/report.js';
import type { HolmesWork } from './manifest.js';
import { KNOWN_ERROR_PATTERNS, knownPatternsForFinding } from './knownErrors.js';

export interface HolmesStoryEntry {
  work: HolmesWork;
  checked: boolean;
  ingested: boolean;
  skipped: boolean;
  skipReason?: string;
  report?: CheckReport;
}

export interface HolmesAccumulatedReport {
  storiesTotal: number;
  storiesChecked: number;
  storiesIngested: number;
  storiesSkipped: number;
  contradictions: number;
  timeline: number;
  newFacts: number;
  uncertain: number;
  stories: HolmesStoryEntry[];
  findings: Array<CheckFinding & { workId: string; storyTitle: string; storyOrder: number }>;
}

export function createEmptyAccumulatedReport(works: HolmesWork[]): HolmesAccumulatedReport {
  return {
    storiesTotal: works.length,
    storiesChecked: 0,
    storiesIngested: 0,
    storiesSkipped: 0,
    contradictions: 0,
    timeline: 0,
    newFacts: 0,
    uncertain: 0,
    stories: works.map((work) => ({
      work,
      checked: false,
      ingested: false,
      skipped: false,
    })),
    findings: [],
  };
}

function pushFindings(
  acc: HolmesAccumulatedReport,
  work: HolmesWork,
  findings: CheckFinding[],
): void {
  for (const finding of findings) {
    acc.findings.push({
      ...finding,
      workId: work.id,
      storyTitle: work.title,
      storyOrder: work.order,
    });
  }
}

export function markStorySkipped(
  acc: HolmesAccumulatedReport,
  work: HolmesWork,
  reason: string,
): void {
  const entry = acc.stories.find((s) => s.work.id === work.id);
  if (!entry) return;
  entry.skipped = true;
  entry.skipReason = reason;
  acc.storiesSkipped += 1;
}

export function accumulateCheckReport(
  acc: HolmesAccumulatedReport,
  work: HolmesWork,
  report: CheckReport,
): void {
  const entry = acc.stories.find((s) => s.work.id === work.id);
  if (!entry) return;

  entry.checked = true;
  entry.report = report;
  acc.storiesChecked += 1;
  acc.contradictions += report.contradictions.length;
  acc.timeline += report.timeline.length;
  acc.newFacts += report.newFacts.length;
  acc.uncertain += report.uncertain.length;

  pushFindings(acc, work, report.contradictions);
  pushFindings(acc, work, report.timeline);
  pushFindings(acc, work, report.newFacts);
  pushFindings(acc, work, report.uncertain);
}

export function markStoryIngested(acc: HolmesAccumulatedReport, work: HolmesWork): void {
  const entry = acc.stories.find((s) => s.work.id === work.id);
  if (!entry) return;
  entry.ingested = true;
  acc.storiesIngested += 1;
}

function renderFinding(f: HolmesAccumulatedReport['findings'][number]): string[] {
  const lines = [`### ${f.summary}`, ''];
  if (f.canon) {
    lines.push(
      `- **canon** ${f.canon.workTitle}, ${f.canon.locator} — "${f.canon.excerpt}"`,
    );
  }
  lines.push(
    `- **draft** ${f.storyTitle} (${f.workId}), ${f.draft.locator} — "${f.draft.quote}"`,
  );
  lines.push(`- ${f.explanation}`, '');
  return lines;
}

/**
 * Render the full Holmes continuity report: narrative sections for known
 * patterns, then a complete cited findings list.
 */
export function renderHolmesContinuityMarkdown(acc: HolmesAccumulatedReport): string {
  const lines: string[] = [
    '# Holmes continuity report',
    '',
    '_Generated by `npm run demo:holmes` — publication-order backfill with pairwise check._',
    '',
    '## Summary',
    '',
    `- Stories in catalog: **${acc.storiesTotal}**`,
    `- Checked before ingest: **${acc.storiesChecked}**`,
    `- Ingested into canon: **${acc.storiesIngested}**`,
    `- Skipped (missing corpus files): **${acc.storiesSkipped}**`,
    `- Contradictions: **${acc.contradictions}**`,
    `- Timeline issues: **${acc.timeline}**`,
    `- New facts: **${acc.newFacts}**`,
    `- Uncertain: **${acc.uncertain}**`,
    '',
  ];

  const narrativeFindings = new Map<string, HolmesAccumulatedReport['findings']>();
  for (const finding of acc.findings) {
    if (finding.kind !== 'contradiction' && finding.kind !== 'timeline') continue;
    for (const pattern of knownPatternsForFinding(finding)) {
      const bucket = narrativeFindings.get(pattern.id) ?? [];
      bucket.push(finding);
      narrativeFindings.set(pattern.id, bucket);
    }
  }

  const matchedPatternIds = new Set(narrativeFindings.keys());
  if (matchedPatternIds.size > 0) {
    lines.push('## Known continuity debates', '');
    for (const pattern of KNOWN_ERROR_PATTERNS) {
      const bucket = narrativeFindings.get(pattern.id);
      if (!bucket || bucket.length === 0) continue;
      lines.push(`### ${pattern.title}`, '', pattern.blurb, '');
      for (const f of bucket) {
        lines.push(...renderFinding(f));
      }
    }
  } else if (acc.findings.length === 0) {
    lines.push(
      '## Known continuity debates',
      '',
      '_No findings yet — run the demo with a populated `HOLMES_CORPUS_ROOT` to populate this section._',
      '',
    );
  }

  lines.push('## All cited findings', '');
  if (acc.findings.length === 0) {
    lines.push('_none_', '');
  } else {
    const sections: Array<[string, HolmesAccumulatedReport['findings']]> = [
      ['Contradictions', acc.findings.filter((f) => f.kind === 'contradiction')],
      ['Timeline issues', acc.findings.filter((f) => f.kind === 'timeline')],
      ['New facts', acc.findings.filter((f) => f.kind === 'new_fact')],
      ['Uncertain', acc.findings.filter((f) => f.kind === 'uncertain')],
    ];
    for (const [title, bucket] of sections) {
      lines.push(`### ${title} (${bucket.length})`, '');
      if (bucket.length === 0) {
        lines.push('_none_', '');
        continue;
      }
      for (const f of bucket) {
        lines.push(...renderFinding(f));
      }
    }
  }

  if (acc.storiesSkipped > 0) {
    lines.push('## Skipped stories', '');
    for (const entry of acc.stories) {
      if (!entry.skipped) continue;
      lines.push(`- **${entry.work.title}** (\`${entry.work.id}\`): ${entry.skipReason ?? 'skipped'}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}
